### PR TITLE
fix: flickering on questions page due to skeleton

### PR DESCRIPTION
**Pull request by Revyy**
Changing the Skeleton to a progress indicator in the QuestionList seems to take care of the flickering.
The progress indicator starts to show after around 300ms, easy to test by applying network throttling in the chrome devtools.

I don't know if using this goes against a design philosophy, if that is the case just ignore this :) 
If you want to go this route I think there could be more places to change this in.

### CODE REVIEW

**Comment by drodil** [comment]
Looks good! There's couple of more places where the Skeleton is used, you want to change those as well? Thanks!

**Comment by Revyy** [comment]
Yeah I can try to locate the rest as well. Will update the PR.

**Comment by Revyy** [comment]
I left the Skeleton in the QuestionHighlightList as it probably does not make sense to have a loader for all three side sections, it looks fine that those sections are just empty.
Also kept the one the QuestionPage for now as it does not flicker in the same way as the others.

**Comment by drodil** [comment]
Alright, this looks great. I will merge and publish!

**Pull request merged**
